export const INIT_CHECKOUT = "INIT_CHECKOUT";
export const CHECKOUT_START = "CHECKOUT_START";
export const SET_STRIPE_PUBLIC_KEY = "SET_STRIPE_PUBLIC_KEY";
export const INIT_CHECKOUT_FAILD = "INIT_CHECKOUT_FAILD";
export const FETCH_SHIPPING_ADDRESSES = "FETCH_SHIPPING_ADDRESSES";
export const FETCH_SHIPPING_ADDRESSES_START= "FETCH_SHIPPING_ADDRESSES_START";
export const SET_SHIPPING_ADDRESSES = "SET_SHIPPING_ADDRESSES";
export const CHECKOUT_FAILD = "CHECKOUT_FAILD";
export const SET_CHOSEN_SHIPPING_ADDRESS = "CHOSEN_SHIPPING_ADDRESS";

export const PURCHASE_CART = "PURCHASE_CART";
export const PURCHASE_CART_START = "PURCHASE_CART_START";
export const PURCHASE_CART_SUCCESS = "PURCHASE_CART_SUCCESS";
export const PURCHASE_CART_FAIL = "PURCHASE_CART_FAIL";