export const INIT_CHECKOUT = "INIT_CHECKOUT";
export const CHECKOUT_START = "CHECKOUT_START";
export const CHECKOUT_SUCCESSED = "CHECKOUT_SUCCESSED"; 
export const CHECKOUT_FAILD = "CHECKOUT_FAILD";
export const CHECKOUT_CANCELED = "CHECKOUT_CANCELED";
export const SET_NEXT_STEP = "SET_NEXT_STEP";

export const FETCH_SHIPPING_ADDRESSES = "FETCH_SHIPPING_ADDRESSES";
export const FETCH_SHIPPING_ADDRESSES_START= "FETCH_SHIPPING_ADDRESSES_START";
export const SET_SHIPPING_ADDRESSES = "SET_SHIPPING_ADDRESSES";

export const SET_CHOSEN_SHIPPING_ADDRESS = "CHOSEN_SHIPPING_ADDRESS";

export const SET_STRIPE_CUSTOMER_TOKEN = "SET_STRIPE_CUSTOMER_TOKEN";

export const INIT_PURCHASE_CART = "INIT_PURCHASE_CART";
export const PURCHASE_CART_START = "PURCHASE_CART_START";
export const PURCHASE_CART_SUCCESS = "PURCHASE_CART_SUCCESS";
export const PURCHASE_CART_FAIL = "PURCHASE_CART_FAIL";