export const INIT_CART = "INIT_CART";
export const SET_CART = "SET_CART";
export const FETCH_CART_FAILED = "FETCH_CART_FAILED";
export const UPDATING_CART_FAILED = "UPDATING_CART_FAILED";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CHANGE_PRODUCT_QUANTITY = "CHANGE_PRODUCT_QUANTITY";